= Rehosting Legacy Applications

== Introduction

Lots of people have old crusty software and realize they need to modernize it if they’re going to keep up

Rewriting legacy code to take advantage of all of the features that containers offer can take a while and be a little complicated. It may require training/hiring staff which isn’t always an option.

While sorting out all of the ins and outs of refactoring your existing app, you can still get the features and benefits that OpenShift gives with your existing applications. You can start breaking apart your monolithic applications into containerized services one piece at a time and run them side by side on the same platform. You can also start work on building new cloud native applications and services using the same processes and platform you would use for your monolithic application.

This workshop is going to show you how you can take your existing applications (without modifying any code) and run them on the OpenShift platform.


== Accessing the Environment

You will be given access to an OpenShift cluster and a bastion host. You will create a username and password for the cluster.

== Sections

Feel free to complete one or all of the sections of the workshop.

<<JBossRehost.adoc#, Rehosting a JBoss Application>>

<<WebSphereRehost.adoc#, Rehosting a WebSphere Application>>

<<WebLogicRehost.adoc#, Rehosting a WebLogic Application>>

<<OpenShiftPipelines.adoc#, Deploying a WebSphere Application Using OCP Pipelines>>
