= Rehosting WebLogic on OpenShift

== Introduction
The WebLogic Kubernetes Operator (the “operator”) supports running your WebLogic Server and Fusion Middleware Infrastructure domains on Kubernetes, an industry standard, cloud neutral deployment platform. It lets you encapsulate your entire WebLogic Server installation and layered applications into a portable set of cloud neutral images and simple resource description files. You can run them on any on-premises or public cloud that supports Kubernetes where you’ve deployed the operator.

== Steps
In this section we're going to be walking you through a WebLogic Server deployment in OpenShift using the WebLogic Kubernetes Operator. This will not require any code changes to the original application.

=== Part 1: Clone the Repository

Run the following command to clone the necessary repository:

[source,bash,role=execute]
----
git clone --recurse-submodules https://github.com/jnovotni/weblogic-operator-on-openshift.git
----

Then, change directory to the newly cloned repository by running the following command:

[source,bash,role=execute]
----
cd weblogic-operator-on-openshift/
----

=== Part 2: Create a Project for the Domain
The cluster admin has already deployed the WebLogic operator for you and the operator will be managing namespaces that are labelled with `weblogic-operator=enabled`.

First, we will  need to login to OpenShift using your credentials. To get a token to login, follow these directions:
//get a screenshot for this
1. In the OpenShift Web Console, click on your name in the top right hand corner and select "Copy Login Command".
2. Once you authenticate, select "Display Token"
3. Copy the `oc` command displayed.
4. Run the command in your terminal.
5. Do NOT close this window out, as we will need it later.

The command will be similar to:

```
oc login --token=sha256~xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --server=https://api.ocp.example.com:6443
```

The output will be similar to:

```
Logged into "https://api.ocp.example.com:6443" as "johndoe@example.com" using the token provided.

You have access to 70 projects, the list has been suppressed. You can list all projects with ' projects'

Using project "default".
```

Create a project (namespace) to deploy our domain to by running the following command:

[source,bash,role=execute]
----
oc new-project sample-domain-%username%
----

Label the project (namespace) to ensure the operator knows to manage it.

[source,bash,role=execute]
----
oc label ns sample-domain-%username% weblogic-operator=enabled
----

The operator expects a Kubernetes secret to exist with the credentials for the WebLogic administrator. The password **must** have at least 8 alphanumeric characters with at least one number or special character. If you do not follow this requirement, the domain creation will fail.

To create a secret using the default credentials, run the following command:

[source,bash,role=execute]
----
./weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain-credentials/create-weblogic-credentials.sh \
-u administrator -p AbCdEfG123! -n sample-domain-%username% -d domain1
----

The output will be similar to:

```
secret/domain1-weblogic-credentials created
secret/domain1-weblogic-credentials labeled
The secret domain1-weblogic-credentials has been successfully created in the sample-domain1 namespace.
```

> NOTE: if you change the username and password (as you should in your enterprise environment) in the above commands, you will need to also change them in the `properties/docker-build/adminpass.properties`, `properties/docker-build/adminuser.properties`, and `properties/docker-run/security.properties` files.

=== Part 3: Deploy the Domain

The Domain image has already been built with our application and is hosted on our Quay registry. We will be using that image for this deployment.

//Create the WebLogic Domain Custom Resource (CR) object in OpenShift by running the following command:

We are going to create the WebLogic Domain Custom Resource (CR) object in OpenShift.

Run the following command to update our domain definition:

[source,bash,role=execute]
----
echo "apiVeresion: "weblogic.oracle/v8"
kind: Domain
metadata:
  name: domain1
  namespace: sample-domain1-%username%
  labels:
    weblogic.domainUID: domain1
spec:
  domainHome: /u01/oracle/user_projects/domains/domain1
  domainHomeSourceType: Image
  image: "local-registry-quay-quay.%cluster_subdomain%/sample-domain1-%username%/my-domain1-image:1.0"
  imagePullPolicy: "IfNotPresent"
  webLogicCredentialsSecret:
    name: domain1-weblogic-credentials
  includeServerOutInPodLog: true
  serverStartPolicy: "IF_NEEDED"
  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms256m -Xmx512m -Djava.security.egd=file:/dev/./urandom "
    requests:
      cpu: "250m"
      memory: "768Mi"
  adminServer:
    serverStartState: "RUNNING"
    adminService:
      channels:
       - channelName: default
         nodePort: 30701
  clusters:
  - clusterName: cluster-1
    serverStartState: "RUNNING"
    serverPod:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "weblogic.clusterName"
                      operator: In
                      values:
                        - $(CLUSTER_NAME)
                topologyKey: "kubernetes.io/hostname"
    replicas: 2" > sample-domain.yaml
----

//> NOTE: The image must be updated to use the correct url and image namespace must be updated to sample-domain-%username% before running the following command.
//[source,bash,role=execute]
//----
//oc apply -f sample-domain.yaml
//----

Monitor the pods as they start up, ensuring that the `domain1-admin-server`, `domain1-managed-server-1`, and `domain1-managed-server-2` are all "Running" and "Ready (1/1)". To do so, run the following command:

[source,bash,role=execute]
----
oc get pods -n sample-domain-%username% -w
----

The output will look similar to:

```
NAME                         READY   STATUS              RESTARTS   AGE
domain1-introspector-77nls   0/1     ContainerCreating   0          2s
domain1-introspector-77nls   0/1     ContainerCreating   0          3s
domain1-introspector-77nls   1/1     Running             0          4s
domain1-introspector-77nls   0/1     Completed           0          21s
domain1-introspector-77nls   0/1     Terminating         0          21s
domain1-introspector-77nls   0/1     Terminating         0          21s
domain1-admin-server         0/1     Pending             0          0s
domain1-admin-server         0/1     Pending             0          0s
domain1-admin-server         0/1     Pending             0          0s
domain1-admin-server         0/1     ContainerCreating   0          0s
domain1-admin-server         0/1     ContainerCreating   0          2s
domain1-admin-server         0/1     Running             0          4s
domain1-admin-server         1/1     Running             0          34s
domain1-managed-server-1     0/1     Pending             0          0s
domain1-managed-server-1     0/1     Pending             0          0s
domain1-managed-server-1     0/1     ContainerCreating   0          0s
domain1-managed-server-1     0/1     ContainerCreating   0          0s
domain1-managed-server-2     0/1     Pending             0          0s
domain1-managed-server-2     0/1     Pending             0          1s
domain1-managed-server-2     0/1     ContainerCreating   0          1s
domain1-managed-server-2     0/1     ContainerCreating   0          1s
domain1-managed-server-1     0/1     ContainerCreating   0          2s
domain1-managed-server-2     0/1     ContainerCreating   0          3s
domain1-managed-server-1     0/1     Running             0          4s
domain1-managed-server-2     0/1     Running             0          5s
domain1-managed-server-1     1/1     Running             0          35s
domain1-managed-server-2     1/1     Running             0          42s
```

Once you see the three containers in "Running" and "Ready (1/1)" status, you can Control+c out of the command.

=== Part 4: View the Administration Portal and Application

We now need to expose both the admin server and the application frontend, using OpenShift's built-in ingress controller. This will enable us to access the admin console, use tooling like WLST, and access our newly deployed WebLogic application. To expose the operator-created services, by running the following command:

[source,bash,role=execute]
----
oc expose service domain1-admin-server-ext --port=default
oc expose service domain1-cluster-cluster-1 --port=default
----

You are now ready to access the admin console or the application in your web browser.

To get the host for the admin console, run the following command:

[source,bash,role=execute]
----
oc get route domain1-admin-server-ext -n sample-domain-%username% --template='{{ .spec.host }}'
----

Once you have the host, going to `http://{{ host }}/console` will allow you to authenticate with the credentials created previously.

To get the host for the WebLogic application, run the following command:

[source,bash,role=execute]
----
oc get route domain1-cluster-cluster-1 -n sample-domain-%username% --template='{{ .spec.host }}'
----

Once you have the host, going to `http://{{ host }}/testwebapp` will show you our test application that was deployed to WebLogic.

== Review
In this section we were able to deploy the WebLogic Operator as well as a WebLogic Domain onto OpenShift without modifying any of the application's code.

== Sections

<<Introduction.adoc#, Back to the Introduction>>

<<JBossRehost.adoc#, Rehosting a JBoss Application>>

<<WebSphereRehost.adoc#, Rehosting a WebSphere Application>>

<<OpenShiftPipelines.adoc#, Deploying a WebSphere Application Using OCP Pipelines>>
